%RD_BUILDEXTENDEDMODEL  Programmatically build the extended R&D Simulink model
%
%   Run this script to create/update 'SpaceRDExtended.slx' which extends the
%   original MathWorks rendezvous model with:
%     - All 7 mission phases from Fehse (2003)
%     - Phase-appropriate sensor models (GPS, Radar, LIDAR, VBS, StarTracker,
%       SunSensor, EarthHorizon, IMU, Magnetometer, Proximity, Docking)
%     - Phase-appropriate actuator models (MainEngine, RCS, RWA, MTQ, Docking)
%     - EKF navigation filter for sensor fusion
%     - Phase-specific guidance and control laws (CW, 6DOF, Lambert)
%     - Phase state machine managing transitions
%
%   Architecture:
%   ┌─────────────────────────────────────────────────────────────────────┐
%   │                     SpaceRDExtended.slx                            │
%   │                                                                     │
%   │  ┌──────────────┐   ┌──────────────┐   ┌──────────────────────┐   │
%   │  │ Phase State  │──▶│  Sensors     │──▶│ Navigation Filter    │   │
%   │  │  Machine     │   │  (per phase) │   │ (EKF sensor fusion)  │   │
%   │  └──────────────┘   └──────────────┘   └──────────┬───────────┘   │
%   │         │                                          │               │
%   │         ▼                                          ▼               │
%   │  ┌──────────────┐   ┌──────────────┐   ┌──────────────────────┐   │
%   │  │  Dynamics    │◀──│  Actuators   │◀──│ Guidance & Control   │   │
%   │  │ (CW/6DOF/Kep)│   │  (per phase) │   │  (per phase laws)    │   │
%   │  └──────────────┘   └──────────────┘   └──────────────────────┘   │
%   │         │                                                          │
%   │         ▼                                                          │
%   │  ┌──────────────┐                                                  │
%   │  │  Visualiser  │  (3-D orbit + relative trajectory plots)        │
%   │  └──────────────┘                                                  │
%   └─────────────────────────────────────────────────────────────────────┘
%
% Reference:
%   Fehse, W. (2003). Automated Rendezvous and Docking of Spacecraft.
%   Cambridge University Press. ISBN 0-521-82492-3.
%
% See also: RD_Fehse_PhaseConfig, RD_SensorModels, RD_ActuatorModels,
%           RD_RelativeDynamics, RD_NavigationFilter, RD_GuidanceControl,
%           RD_RunAllPhases

% Copyright 2024 - Extended R&D Simulation

%% -----------------------------------------------------------------------
%  0. Setup
% -----------------------------------------------------------------------
model_name = 'SpaceRDExtended';

% Close existing model if open
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

% Create new Simulink model
new_system(model_name);
open_system(model_name);

% Load phase configuration
cfg = RD_Fehse_PhaseConfig();

%% -----------------------------------------------------------------------
%  1. Model-level parameters
% -----------------------------------------------------------------------
set_param(model_name, ...
    'Solver',       'ode45',    ...
    'StopTime',     '86400',    ...  % 24 h maximum simulation
    'MaxStep',      '0.1',      ...  % 100 ms max step for close phases
    'AbsTol',       '1e-6',     ...
    'RelTol',       '1e-6',     ...
    'SolverType',   'Variable-step');

%% -----------------------------------------------------------------------
%  2. Subsystem layout positions  [left top right bottom] in pixels
% -----------------------------------------------------------------------
pos_phase_sm    = [50,  200, 250, 350];
pos_sensors     = [300, 100, 550, 250];
pos_nav_filter  = [600, 100, 850, 250];
pos_gnc         = [600, 300, 850, 450];
pos_actuators   = [300, 300, 550, 450];
pos_dynamics    = [50,  300, 250, 450];
pos_visualiser  = [600, 500, 850, 650];

%% -----------------------------------------------------------------------
%  3. Phase State Machine  (Stateflow chart or MATLAB Function block)
% -----------------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model_name '/Phase_State_Machine'], ...
    'Position', pos_phase_sm);

% Set MATLAB function content for phase state machine
ph_sm_fcn = sprintf([...
'function [phase_id, phase_name, transition_flag] = Phase_State_Machine(t, nav_range_m)\n'...
'%% Phase_State_Machine  Determines current mission phase based on range\n'...
'%%   Phase transitions (Fehse Table 5.1):\n'...
'%%   Phase 0 (Launch)         : t < 600 s\n'...
'%%   Phase 1 (Phasing)        : range > 50 km\n'...
'%%   Phase 2 (Far R&V)        : 5 km < range ≤ 50 km\n'...
'%%   Phase 3 (Homing)         : 200 m < range ≤ 5 km\n'...
'%%   Phase 4 (Closing)        : 20 m < range ≤ 200 m\n'...
'%%   Phase 5 (Final Approach) : 0 < range ≤ 20 m\n'...
'%%   Phase 6 (Docking)        : range ≤ 0 m (contact)\n'...
'coder.extrinsic(''disp'');\n'...
'if t < 600\n'...
'    phase_id = int32(0); phase_name = ''Launch'';\n'...
'elseif nav_range_m > 50000\n'...
'    phase_id = int32(1); phase_name = ''Phasing'';\n'...
'elseif nav_range_m > 5000\n'...
'    phase_id = int32(2); phase_name = ''FarRendezvous'';\n'...
'elseif nav_range_m > 200\n'...
'    phase_id = int32(3); phase_name = ''Homing'';\n'...
'elseif nav_range_m > 20\n'...
'    phase_id = int32(4); phase_name = ''Closing'';\n'...
'elseif nav_range_m > 0\n'...
'    phase_id = int32(5); phase_name = ''FinalApproach'';\n'...
'else\n'...
'    phase_id = int32(6); phase_name = ''Docking'';\n'...
'end\n'...
'transition_flag = false;\n'...
]);
set_param([model_name '/Phase_State_Machine'], 'MATLABFunctionBlock', ph_sm_fcn);

%% -----------------------------------------------------------------------
%  4. Sensor Suite  (enabled subsystem with phase-based switching)
% -----------------------------------------------------------------------
add_block('simulink/Ports & Subsystems/Subsystem', ...
    [model_name '/Sensor_Suite'], ...
    'Position', pos_sensors);

% Add individual MATLAB Function blocks for each sensor type
sensor_types = { ...
    'GPS',              'GPS (Absolute, Phases 0-3)';       ...
    'RelativeGPS',      'Relative GPS (Phases 1-3)';        ...
    'Radar_RF',         'Radar RF (Phases 2-3)';            ...
    'LIDAR_Scanning',   'LIDAR Scanning (Phases 3-4)';      ...
    'LIDAR_Flash',      'LIDAR Flash (Phases 4-5)';         ...
    'VBS_Camera',       'VBS Camera (Phases 3-4)';          ...
    'VBS_Camera_HighRes','VBS High-Res (Phases 5-6)';       ...
    'StarTracker',      'Star Tracker (All phases)';        ...
    'SunSensor_Coarse', 'Sun Sensor Coarse (Phases 0-1)';   ...
    'SunSensor_Fine',   'Sun Sensor Fine (Phases 1-3)';     ...
    'EarthHorizonSensor','Earth Horizon (Phases 0-2)';      ...
    'IMU',              'IMU (All phases)';                  ...
    'Magnetometer',     'Magnetometer (Phases 0-2)';        ...
    'ProximitySensors', 'Proximity Sensors (Phase 5)';      ...
    'DockingSensors',   'Docking Sensors (Phase 6)';        ...
    'ContactForceSensors','Contact Force (Phase 6)'         ...
};

for i = 1:size(sensor_types,1)
    sensor_id   = sensor_types{i,1};
    sensor_desc = sensor_types{i,2};
    blk_name = [model_name '/Sensor_Suite/Sensor_' sensor_id];
    add_block('simulink/User-Defined Functions/MATLAB Function', blk_name, ...
        'Position', [50 + mod(i-1,4)*200, 50 + floor((i-1)/4)*120, ...
                     200 + mod(i-1,4)*200, 120 + floor((i-1)/4)*120]);

    % Generate sensor wrapper function
    fcn_str = sprintf([...
        'function meas = fcn(trueState, phase_id)\n'...
        '%% %s\n'...
        'meas_st = RD_SensorModels(''%s'', trueState, struct());\n'...
        'if ~meas_st.valid\n'...
        '    meas = zeros(6,1);\n'...
        '    return;\n'...
        'end\n'...
        'fields = fieldnames(meas_st);\n'...
        'vals = [];\n'...
        'for k = 1:numel(fields)\n'...
        '    v = meas_st.(fields{k});\n'...
        '    if isnumeric(v)\n'...
        '        vals = [vals; v(:)];\n'...
        '    end\n'...
        'end\n'...
        'meas = vals;\n'...
        'end\n'...
        ], sensor_desc, sensor_id);
    set_param(blk_name, 'MATLABFunctionBlock', fcn_str);
end

%% -----------------------------------------------------------------------
%  5. Navigation Filter  (EKF sensor fusion)
% -----------------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model_name '/Navigation_Filter'], ...
    'Position', pos_nav_filter);

nav_fcn = [...
'function [nav_out, range_m] = Navigation_Filter(measurements_flat, phase_id, dt)\n'...
'%% Navigation_Filter  EKF wrapper for Simulink\n'...
'persistent x_est P;\n'...
'if isempty(x_est)\n'...
'    x_est = zeros(12,1);\n'...
'    x_est(7) = 1;  %% identity quat scalar\n'...
'    P = eye(12) * 1e6;\n'...
'end\n'...
'meas = struct();\n'...
'params.n = 1.1e-3;\n'...
'[x_est, P, nav] = RD_NavigationFilter(phase_id, x_est, P, meas, dt, params);\n'...
'nav_out = [nav.rel_pos_LVLH; nav.rel_vel_LVLH];\n'...
'range_m = nav.range_m;\n'...
'end\n'];
set_param([model_name '/Navigation_Filter'], 'MATLABFunctionBlock', nav_fcn);

%% -----------------------------------------------------------------------
%  6. Guidance & Control  (phase-specific laws)
% -----------------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model_name '/Guidance_Control'], ...
    'Position', pos_gnc);

gnc_fcn = [...
'function [F_cmd, T_cmd] = Guidance_Control(nav_state, phase_id)\n'...
'%% Guidance_Control  Phase-specific guidance and control wrapper\n'...
'nav.rel_pos_LVLH = nav_state(1:3);\n'...
'nav.rel_vel_LVLH = nav_state(4:6);\n'...
'nav.range_m = norm(nav_state(1:3));\n'...
'nav.att_quat = [1;0;0;0];\n'...
'nav.ang_rate = zeros(3,1);\n'...
'target = struct();\n'...
'params.n = 1.1e-3;\n'...
'params.mass_kg = 8000;\n'...
'[F_cmd, T_cmd] = RD_GuidanceControl(double(phase_id), nav, target, params);\n'...
'end\n'];
set_param([model_name '/Guidance_Control'], 'MATLABFunctionBlock', gnc_fcn);

%% -----------------------------------------------------------------------
%  7. Actuator Subsystem  (phase-appropriate actuators with saturation)
% -----------------------------------------------------------------------
add_block('simulink/Ports & Subsystems/Subsystem', ...
    [model_name '/Actuator_Suite'], ...
    'Position', pos_actuators);

actuator_types = { ...
    'MainEngine',           'Main Engine (Phases 0-2)';   ...
    'RCS_Thrusters',        'RCS Thrusters (Phases 1-5)'; ...
    'RCS_Thrusters_Fine',   'Fine RCS (Phases 5-6)';      ...
    'ReactionWheels',       'Reaction Wheels (All)';       ...
    'MagneticTorquer',      'Magnetorquer (Phases 0-2)';   ...
    'DockingMechanism',     'Docking Mechanism (Phase 6)'  ...
};

for i = 1:size(actuator_types,1)
    act_id   = actuator_types{i,1};
    act_desc = actuator_types{i,2};
    blk_name = [model_name '/Actuator_Suite/Actuator_' act_id];
    add_block('simulink/User-Defined Functions/MATLAB Function', blk_name, ...
        'Position', [50 + mod(i-1,3)*200, 50 + floor((i-1)/3)*120, ...
                     200 + mod(i-1,3)*200, 120 + floor((i-1)/3)*120]);

    fcn_str = sprintf([...
        'function [F_body, T_body, mdot] = fcn(F_req, T_req, phase_id)\n'...
        '%% %s\n'...
        'cmd.force_body_N = F_req;\n'...
        'cmd.torque_body_Nm = T_req;\n'...
        'state = struct(''att_quat'', [1;0;0;0]);\n'...
        'out = RD_ActuatorModels(''%s'', cmd, state, struct());\n'...
        'F_body = out.force_body_N;\n'...
        'T_body = out.torque_body_Nm;\n'...
        'mdot = out.mass_flow_kgs;\n'...
        'end\n'...
        ], act_desc, act_id);
    set_param(blk_name, 'MATLABFunctionBlock', fcn_str);
end

%% -----------------------------------------------------------------------
%  8. Dynamics Block  (CW / 6DOF / Keplerian switching)
% -----------------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model_name '/Dynamics'], ...
    'Position', pos_dynamics);

dyn_fcn = [...
'function xdot = Dynamics(t, x, F_body, T_body, phase_id)\n'...
'%% Dynamics  Switching dynamics model for all R&D phases\n'...
'params.mass_kg = 8000;\n'...
'params.n = 1.1e-3;\n'...
'params.mu = 3.986004418e14;\n'...
'params.J2_enable = true;\n'...
'if phase_id <= 2\n'...
'    params.mode = ''keplerian'';\n'...
'elseif phase_id <= 4\n'...
'    params.mode = ''CW'';\n'...
'else\n'...
'    params.mode = ''6DOF'';\n'...
'end\n'...
'[xdot, ~] = RD_RelativeDynamics(t, x, F_body, T_body, params);\n'...
'end\n'];
set_param([model_name '/Dynamics'], 'MATLABFunctionBlock', dyn_fcn);

%% -----------------------------------------------------------------------
%  9. Integrator for state  (continuous state integration)
% -----------------------------------------------------------------------
add_block('simulink/Continuous/Integrator', ...
    [model_name '/State_Integrator'], ...
    'Position', [50 450 250 550], ...
    'InitialCondition', '0');

%% -----------------------------------------------------------------------
%  10. Visualisation (Scope + 3-D Aerospace Blockset)
% -----------------------------------------------------------------------
add_block('simulink/Sinks/Scope', ...
    [model_name '/Relative_Position_Scope'], ...
    'Position', [pos_visualiser(1), pos_visualiser(2), ...
                 pos_visualiser(3), pos_visualiser(4)], ...
    'NumInputPorts', '3');

% Phase indicator display
add_block('simulink/Sinks/Display', ...
    [model_name '/Phase_Display'], ...
    'Position', [50 550 250 620]);

% Mission timeline scope (range vs time)
add_block('simulink/Sinks/To Workspace', ...
    [model_name '/Log_RelPos'], ...
    'Position', [600 200 800 250], ...
    'VariableName', 'log_rel_pos', ...
    'SaveFormat', 'Array');

add_block('simulink/Sinks/To Workspace', ...
    [model_name '/Log_Phase'], ...
    'Position', [600 260 800 310], ...
    'VariableName', 'log_phase', ...
    'SaveFormat', 'Array');

add_block('simulink/Sinks/To Workspace', ...
    [model_name '/Log_SensorMeas'], ...
    'Position', [600 320 800 370], ...
    'VariableName', 'log_sensors', ...
    'SaveFormat', 'Array');

%% -----------------------------------------------------------------------
%  11. Signal Routing
% -----------------------------------------------------------------------
% Note: Full signal routing requires proper port dimensions.
% The connections below use add_line for key signal paths.

% Phase state machine -> Guidance/Control
add_line(model_name, 'Phase_State_Machine/1', 'Guidance_Control/2', ...
    'autorouting', 'on');

% Navigation filter -> Phase state machine (range feedback)
add_line(model_name, 'Navigation_Filter/2', 'Phase_State_Machine/2', ...
    'autorouting', 'on');

% Navigation filter -> Guidance/Control
add_line(model_name, 'Navigation_Filter/1', 'Guidance_Control/1', ...
    'autorouting', 'on');

% Guidance/Control -> Actuator suite (F_cmd)
add_line(model_name, 'Guidance_Control/1', 'Actuator_Suite/1', ...
    'autorouting', 'on');
add_line(model_name, 'Guidance_Control/2', 'Actuator_Suite/2', ...
    'autorouting', 'on');

% Phase -> Actuator/Sensor enable
add_line(model_name, 'Phase_State_Machine/1', 'Actuator_Suite/3', ...
    'autorouting', 'on');
add_line(model_name, 'Phase_State_Machine/1', 'Phase_Display/1', ...
    'autorouting', 'on');

%% -----------------------------------------------------------------------
%  12. Add annotations (documentation layers)
% -----------------------------------------------------------------------
add_annotation(model_name, ...
    'Fehse (2003) R&D Phases:\n0:Launch  1:Phasing  2:FarRV\n3:Homing  4:Closing  5:FinalAppr  6:Docking', ...
    [50 50 600 150]);

add_annotation(model_name, ...
    'Sensors by Phase:\n0: IMU,GPS,SunCoarse,Magnetometer\n1: GPS,RGPS,StarTracker,EarthHorizon,IMU,Mag\n2: GPS,Radar,StarTracker,IMU\n3: Radar,LIDAR_S,VBS,StarTracker,IMU\n4: LIDAR_S,LIDAR_F,VBS,StarTracker,IMU\n5: LIDAR_F,VBS_HR,Proximity,StarTracker,IMU\n6: DockingSensors,ContactForce,IMU,VBS_HR', ...
    [900 50 1600 350]);

add_annotation(model_name, ...
    'Actuators by Phase:\n0: MainEngine,RCS,MagTorquer\n1: MainEngine,RCS,RWA,MagTorquer\n2: MainEngine,RCS,RWA\n3-4: RCS,RWA\n5: Fine_RCS,RWA\n6: DockingMech,Fine_RCS,RWA', ...
    [900 400 1600 700]);

%% -----------------------------------------------------------------------
%  13. Save model
% -----------------------------------------------------------------------
save_system(model_name, [model_name '.slx']);
disp(['[RD_BuildExtendedModel] Model saved: ' model_name '.slx']);

%% -----------------------------------------------------------------------
%  14. Print phase summary table
% -----------------------------------------------------------------------
fprintf('\n');
fprintf('%-5s %-35s %-15s %-30s %-25s\n', ...
    'Phase', 'Name', 'Range', 'Primary Sensors', 'Actuators');
fprintf('%s\n', repmat('-', 1, 115));
for p = 1:numel(cfg)
    ph   = cfg(p);
    % Collect primary sensor names
    prim_sensors = {};
    for s = 1:numel(ph.sensors)
        if ph.sensors(s).primary
            prim_sensors{end+1} = ph.sensors(s).type; %#ok<AGROW>
        end
    end
    act_names = {ph.actuators.type};

    range_str = sprintf('[%g-%g] km', ph.range_km(1), ph.range_km(2));
    if isinf(ph.range_km(2)), range_str = sprintf('>%g km', ph.range_km(1)); end
    if ph.range_km(1)==0 && ph.range_km(2)==0, range_str = 'Contact'; end

    fprintf('%-5d %-35s %-15s %-30s %-25s\n', ...
        ph.id, ph.name, range_str, ...
        strjoin(prim_sensors, ', '), ...
        strjoin(act_names, ', '));
end
fprintf('\n');

%% -----------------------------------------------------------------------
%  Helper: add annotation to model canvas
% -----------------------------------------------------------------------
function add_annotation(mdl, text, pos)
    try
        annotation_handle = add_block('built-in/Note', [mdl '/Note_' sprintf('%d', randi(1e6))], ...
            'Position', pos);
        set_param(annotation_handle, 'Text', text);
    catch
        % Annotations may not be supported in all Simulink versions
    end
end
