function cfg = RD_Fehse_PhaseConfig()
%RD_FEHSE_PHASECONFIG  Returns the complete R&D phase configuration
%   based on Fehse, W. "Automated Rendezvous and Docking of Spacecraft"
%   Cambridge University Press, 2003.
%
%   cfg = RD_Fehse_PhaseConfig() returns a struct array where each element
%   corresponds to one mission phase. Each phase contains:
%       .name           - Phase name
%       .id             - Phase index (1-based)
%       .range_km       - [min max] range from target in km
%       .duration_s     - Typical phase duration in seconds
%       .dynamics       - 'keplerian' | 'CW' | '6DOF'
%       .sensors        - Struct array of sensors used in this phase
%       .actuators      - Struct array of actuators used in this phase
%       .nav_mode       - Navigation mode used
%       .guidance_mode  - Guidance strategy
%       .control_mode   - Control mode
%
%   Sensor fields:
%       .type           - Sensor type string
%       .primary        - true = primary (false = backup/secondary)
%       .output         - What it measures (cell array of strings)
%       .accuracy       - Typical 1-sigma accuracy (struct)
%       .update_rate_Hz - Measurement update rate in Hz
%
%   Actuator fields:
%       .type           - Actuator type string
%       .function       - 'orbit' | 'attitude' | 'both'
%       .max_force_N    - Maximum force magnitude (NaN for torque-only)
%       .max_torque_Nm  - Maximum torque magnitude (NaN for force-only)
%       .Isp_s          - Specific impulse in seconds (NaN if not applicable)
%
% Reference:
%   Fehse, W. (2003). Automated Rendezvous and Docking of Spacecraft.
%   Cambridge University Press. ISBN 0-521-82492-3.
%
% See also: RD_SensorModels, RD_ActuatorModels, RD_BuildExtendedModel

% Copyright 2024 - Extended R&D Simulation

%% -----------------------------------------------------------------------
%  PHASE 0 : LAUNCH & ASCENT (lift-off → parking orbit insertion)
% -----------------------------------------------------------------------
p = 1;
cfg(p).name          = 'Launch and Ascent';
cfg(p).id            = 0;
cfg(p).range_km      = [Inf Inf];   % N/A (absolute, not relative)
cfg(p).duration_s    = 600;         % ~10 min to LEO
cfg(p).dynamics      = 'keplerian';
cfg(p).nav_mode      = 'INS_GPS';
cfg(p).guidance_mode = 'ascent_trajectory';
cfg(p).control_mode  = 'attitude_autopilot';

cfg(p).sensors = struct( ...
    'type',        {'IMU','GPS','SunSensor_Coarse','Magnetometer'}, ...
    'primary',     {true, true, false, false}, ...
    'output',      {{'ang_rate','accel'},{'pos_ECI','vel_ECI'}, ...
                    {'sun_vec'},{'mag_field'}}, ...
    'accuracy',    {struct('ang_rate_dph', 0.01, 'accel_ug', 50), ...
                    struct('pos_m', 10, 'vel_ms', 0.1), ...
                    struct('angle_deg', 1.0), ...
                    struct('field_nT', 100)}, ...
    'update_rate_Hz', {400, 1, 4, 10} ...
);

cfg(p).actuators = struct( ...
    'type',         {'MainEngine','RCS_Thrusters','MagneticTorquer'}, ...
    'function',     {'orbit','both','attitude'}, ...
    'max_force_N',  {900e3, 400, NaN}, ...
    'max_torque_Nm',{NaN,   50,  10}, ...
    'Isp_s',        {340,   220, NaN} ...
);

%% -----------------------------------------------------------------------
%  PHASE 1 : PHASING  (parking orbit → ~50 km behind target)
%  Fehse Ch.5 – Far-range rendezvous using Hohmann-type transfers
% -----------------------------------------------------------------------
p = p + 1;
cfg(p).name          = 'Phasing';
cfg(p).id            = 1;
cfg(p).range_km      = [50 Inf];     % > 50 km
cfg(p).duration_s    = 3600*6;       % ~6 h (depends on phase angle)
cfg(p).dynamics      = 'keplerian';
cfg(p).nav_mode      = 'GPS_StarTracker';
cfg(p).guidance_mode = 'Hohmann_transfer';
cfg(p).control_mode  = 'impulsive_dV';

cfg(p).sensors = struct( ...
    'type',        {'GPS','RelativeGPS','StarTracker', ...
                    'EarthHorizonSensor','SunSensor_Fine', ...
                    'IMU','Magnetometer'}, ...
    'primary',     {true, true, true, false, false, true, false}, ...
    'output',      {{'pos_ECI','vel_ECI'}, ...
                    {'rel_pos_ECI','rel_vel_ECI'}, ...
                    {'attitude_quat','ang_rate'}, ...
                    {'nadir_vec'}, ...
                    {'sun_vec_body'}, ...
                    {'ang_rate','accel'}, ...
                    {'mag_field'}}, ...
    'accuracy',    {struct('pos_m',10,'vel_ms',0.1), ...
                    struct('rel_pos_m',5,'rel_vel_ms',0.05), ...
                    struct('att_arcsec',5,'rate_as',0.5), ...
                    struct('angle_deg',0.1), ...
                    struct('angle_deg',0.05), ...
                    struct('ang_rate_dph',0.01,'accel_ug',50), ...
                    struct('field_nT',100)}, ...
    'update_rate_Hz', {1, 1, 4, 4, 4, 400, 10} ...
);

cfg(p).actuators = struct( ...
    'type',         {'MainEngine','RCS_Thrusters', ...
                     'ReactionWheels','MagneticTorquer'}, ...
    'function',     {'orbit','both','attitude','attitude'}, ...
    'max_force_N',  {500, 400, NaN, NaN}, ...
    'max_torque_Nm',{NaN,  50,  0.5,  10}, ...
    'Isp_s',        {340,  220, NaN, NaN} ...
);

%% -----------------------------------------------------------------------
%  PHASE 2 : FAR-RANGE RENDEZVOUS  (~50 km → ~5 km)
%  Fehse Ch.5 – Radar acquisition, ground-track synchronisation
% -----------------------------------------------------------------------
p = p + 1;
cfg(p).name          = 'Far-Range Rendezvous';
cfg(p).id            = 2;
cfg(p).range_km      = [5 50];
cfg(p).duration_s    = 3600*2;       % ~2 h
cfg(p).dynamics      = 'keplerian';
cfg(p).nav_mode      = 'GPS_Radar_StarTracker';
cfg(p).guidance_mode = 'radial_approach';
cfg(p).control_mode  = 'finite_burn';

cfg(p).sensors = struct( ...
    'type',        {'GPS','RelativeGPS','Radar_RF', ...
                    'StarTracker','SunSensor_Fine','IMU'}, ...
    'primary',     {true, true, true, true, false, true}, ...
    'output',      {{'pos_ECI','vel_ECI'}, ...
                    {'rel_pos_ECI','rel_vel_ECI'}, ...
                    {'range_m','range_rate_ms','az_deg','el_deg'}, ...
                    {'attitude_quat'}, ...
                    {'sun_vec_body'}, ...
                    {'ang_rate','accel'}}, ...
    'accuracy',    {struct('pos_m',10,'vel_ms',0.1), ...
                    struct('rel_pos_m',5,'rel_vel_ms',0.05), ...
                    struct('range_m',20,'range_rate_ms',0.2, ...
                           'az_mdeg',50,'el_mdeg',50), ...
                    struct('att_arcsec',5), ...
                    struct('angle_deg',0.05), ...
                    struct('ang_rate_dph',0.01,'accel_ug',50)}, ...
    'update_rate_Hz', {1, 1, 0.1, 4, 4, 400} ...
);

cfg(p).actuators = struct( ...
    'type',         {'MainEngine','RCS_Thrusters','ReactionWheels'}, ...
    'function',     {'orbit','both','attitude'}, ...
    'max_force_N',  {500, 400, NaN}, ...
    'max_torque_Nm',{NaN,  50, 0.5}, ...
    'Isp_s',        {340,  220, NaN} ...
);

%% -----------------------------------------------------------------------
%  PHASE 3 : HOMING / CLOSE-RANGE RENDEZVOUS  (~5 km → ~200 m)
%  Fehse Ch.6 – Optical sensor acquisition, CW guidance
% -----------------------------------------------------------------------
p = p + 1;
cfg(p).name          = 'Homing (Close-Range Rendezvous)';
cfg(p).id            = 3;
cfg(p).range_km      = [0.2 5];
cfg(p).duration_s    = 3600;         % ~1 h
cfg(p).dynamics      = 'CW';        % Clohessy-Wiltshire
cfg(p).nav_mode      = 'Radar_LIDAR_StarTracker';
cfg(p).guidance_mode = 'CW_lambert';
cfg(p).control_mode  = 'continuous_thrust';

cfg(p).sensors = struct( ...
    'type',        {'Radar_RF','LIDAR_Scanning','VBS_Camera', ...
                    'StarTracker','IMU','RelativeGPS'}, ...
    'primary',     {true, true, false, true, true, false}, ...
    'output',      {{'range_m','range_rate_ms','az_deg','el_deg'}, ...
                    {'range_m','bearing_deg','LOS_vec'}, ...
                    {'rel_pos_m','rel_att_quat','LOS_vec'}, ...
                    {'attitude_quat'}, ...
                    {'ang_rate','accel'}, ...
                    {'rel_pos_ECI','rel_vel_ECI'}}, ...
    'accuracy',    {struct('range_m',5,'range_rate_ms',0.1, ...
                           'az_mdeg',30,'el_mdeg',30), ...
                    struct('range_m',1,'bearing_mdeg',10,'LOS_mrad',5), ...
                    struct('rel_pos_m',2,'att_deg',0.5,'LOS_mrad',3), ...
                    struct('att_arcsec',5), ...
                    struct('ang_rate_dph',0.01,'accel_ug',50), ...
                    struct('rel_pos_m',5,'rel_vel_ms',0.05)}, ...
    'update_rate_Hz', {0.5, 1, 1, 4, 400, 1} ...
);

cfg(p).actuators = struct( ...
    'type',         {'RCS_Thrusters','ReactionWheels'}, ...
    'function',     {'both','attitude'}, ...
    'max_force_N',  {400, NaN}, ...
    'max_torque_Nm',{ 50, 0.5}, ...
    'Isp_s',        {220, NaN} ...
);

%% -----------------------------------------------------------------------
%  PHASE 4 : CLOSING / APPROACH  (~200 m → ~20 m)
%  Fehse Ch.6 – Forced motion along V-bar or R-bar approach corridor
% -----------------------------------------------------------------------
p = p + 1;
cfg(p).name          = 'Closing (Forced Motion Approach)';
cfg(p).id            = 4;
cfg(p).range_km      = [0.02 0.2];   % 20 m – 200 m
cfg(p).duration_s    = 1800;         % ~30 min
cfg(p).dynamics      = 'CW';
cfg(p).nav_mode      = 'LIDAR_VBS_StarTracker';
cfg(p).guidance_mode = 'Vbar_approach';
cfg(p).control_mode  = 'continuous_thrust';

cfg(p).sensors = struct( ...
    'type',        {'LIDAR_Scanning','LIDAR_Flash','VBS_Camera', ...
                    'StarTracker','IMU'}, ...
    'primary',     {true, false, true, true, true}, ...
    'output',      {{'range_m','bearing_deg','LOS_vec'}, ...
                    {'range_m','range_rate_ms','3D_map'}, ...
                    {'rel_pos_m','rel_att_quat','LOS_vec', ...
                     'feature_points'}, ...
                    {'attitude_quat'}, ...
                    {'ang_rate','accel'}}, ...
    'accuracy',    {struct('range_m',0.5,'bearing_mdeg',5,'LOS_mrad',2), ...
                    struct('range_m',0.2,'range_rate_ms',0.02), ...
                    struct('rel_pos_m',0.5,'att_deg',0.1,'LOS_mrad',1), ...
                    struct('att_arcsec',5), ...
                    struct('ang_rate_dph',0.01,'accel_ug',50)}, ...
    'update_rate_Hz', {1, 5, 5, 4, 400} ...
);

cfg(p).actuators = struct( ...
    'type',         {'RCS_Thrusters','ReactionWheels'}, ...
    'function',     {'both','attitude'}, ...
    'max_force_N',  {400, NaN}, ...
    'max_torque_Nm',{ 50, 0.5}, ...
    'Isp_s',        {220, NaN} ...
);

%% -----------------------------------------------------------------------
%  PHASE 5 : FINAL APPROACH  (~20 m → contact)
%  Fehse Ch.6/7 – Fine 6-DOF control, corridor constraints
% -----------------------------------------------------------------------
p = p + 1;
cfg(p).name          = 'Final Approach';
cfg(p).id            = 5;
cfg(p).range_km      = [0 0.02];     % 0 – 20 m
cfg(p).duration_s    = 600;          % ~10 min
cfg(p).dynamics      = '6DOF';
cfg(p).nav_mode      = 'LIDAR_VBS_ProximitySensors';
cfg(p).guidance_mode = 'corridor_constrained';
cfg(p).control_mode  = '6DOF_fine';

cfg(p).sensors = struct( ...
    'type',        {'LIDAR_Flash','VBS_Camera_HighRes', ...
                    'ProximitySensors','StarTracker','IMU'}, ...
    'primary',     {true, true, false, true, true}, ...
    'output',      {{'range_m','range_rate_ms','3D_map','rel_att_quat'}, ...
                    {'rel_pos_m','rel_att_quat','LOS_vec', ...
                     'docking_port_pose'}, ...
                    {'gap_m','contact_flag'}, ...
                    {'attitude_quat'}, ...
                    {'ang_rate','accel'}}, ...
    'accuracy',    {struct('range_m',0.05,'range_rate_ms',0.005, ...
                           'att_deg',0.05), ...
                    struct('rel_pos_m',0.05,'att_deg',0.02,'LOS_mrad',0.5), ...
                    struct('gap_m',0.01,'contact',true), ...
                    struct('att_arcsec',5), ...
                    struct('ang_rate_dph',0.005,'accel_ug',20)}, ...
    'update_rate_Hz', {10, 10, 100, 4, 400} ...
);

cfg(p).actuators = struct( ...
    'type',         {'RCS_Thrusters_Fine','ReactionWheels'}, ...
    'function',     {'both','attitude'}, ...
    'max_force_N',  {40, NaN}, ...
    'max_torque_Nm',{ 5, 0.5}, ...
    'Isp_s',        {220, NaN} ...
);

%% -----------------------------------------------------------------------
%  PHASE 6 : DOCKING  (contact → rigidisation)
%  Fehse Ch.7 – Capture, attenuation, rigidisation
% -----------------------------------------------------------------------
p = p + 1;
cfg(p).name          = 'Docking';
cfg(p).id            = 6;
cfg(p).range_km      = [0 0];
cfg(p).duration_s    = 300;          % ~5 min
cfg(p).dynamics      = '6DOF';
cfg(p).nav_mode      = 'DockingSensors_IMU';
cfg(p).guidance_mode = 'null_rates';
cfg(p).control_mode  = 'contact_dynamics';

cfg(p).sensors = struct( ...
    'type',        {'DockingSensors','ContactForceSensors', ...
                    'IMU','VBS_Camera_HighRes'}, ...
    'primary',     {true, true, true, false}, ...
    'output',      {{'alignment_mm','attitude_mrad','capture_flag'}, ...
                    {'force_N','torque_Nm','contact_pts'}, ...
                    {'ang_rate','accel'}, ...
                    {'docking_port_pose'}}, ...
    'accuracy',    {struct('align_mm',5,'att_mrad',2), ...
                    struct('force_N',0.5,'torque_Nm',0.1), ...
                    struct('ang_rate_dph',0.005,'accel_ug',20), ...
                    struct('rel_pos_m',0.02,'att_deg',0.01)}, ...
    'update_rate_Hz', {100, 1000, 400, 10} ...
);

cfg(p).actuators = struct( ...
    'type',         {'DockingMechanism','RCS_Thrusters_Fine', ...
                     'ReactionWheels'}, ...
    'function',     {'docking','attitude','attitude'}, ...
    'max_force_N',  {NaN, 40, NaN}, ...
    'max_torque_Nm',{NaN,  5, 0.5}, ...
    'Isp_s',        {NaN, 220, NaN} ...
);

end
